/**
 * Cluster Types
 *
 * Types for article clustering based on embeddings.
 */

/**
 * A cluster of related articles
 */
export interface Cluster {
  /** Unique identifier for the cluster */
  id: string;
  /** Human-readable name (generated by LLM) */
  name: string | null;
  /** Centroid vector (average of all article embeddings) */
  centroid: number[];
  /** IDs of articles in this cluster */
  articleIds: string[];
  /** Cluster status */
  status: "active" | "archived";
  /** When the cluster was created */
  createdAt: string;
  /** When the cluster was last updated */
  updatedAt: string;
}

/**
 * Result of clustering operation
 */
export interface ClusteringResult {
  /** Clusters found */
  clusters: Cluster[];
  /** Article IDs that didn't fit any cluster (noise) */
  noise: string[];
  /** Statistics about the clustering */
  stats: {
    totalArticles: number;
    clusteredArticles: number;
    noiseArticles: number;
    clusterCount: number;
  };
}

/**
 * Configuration for DBSCAN clustering
 */
export interface ClusteringConfig {
  /** Minimum number of articles to form a cluster */
  minClusterSize: number;
  /** Minimum samples in neighborhood for core points */
  minSamples: number;
  /** Max cosine distance for neighbors (lower = stricter, default 0.25) */
  epsilon?: number;
  /** Maximum articles per cluster to prevent mega-clusters */
  maxClusterSize?: number;
}

/**
 * Article with embedding for clustering
 */
export interface ArticleForClustering {
  id: string;
  title: string;
  excerpt: string;
  keywords: string;
  embedding: number[];
}

/**
 * Storage format for clusters in Vercel Blob
 */
export interface ClustersFile {
  version: 1;
  lastClustered: string;
  totalClusters: number;
  clusters: Cluster[];
}

